name = "Pixpression"
license = "MIT"
licenselink = "https://github.com/michaeljaggers/pixpression/blob/master/LICENSE"
description = "Pixpression Design Studio Website"
homepage = "https://pixpression.com"
tags = []
features = ['bootstrap','responsive']
min_version = "0.64.0"

[author]
  name = "W Michael Jaggers"
  homepage = "https://michaeljaggers.com/"

[original]
  name = "kross"
  homepage = "https://themefisher.com/products/kross-creative-portfolio-template/"